# Site settings
title: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.primetravel.am/" # the base hostname & protocol for your site
email: "info@primetravel.am"
# Build settings
markdown: kramdown
