---
title: Prime Travel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://primetravel.am
email: info@primetravel.am
markdown: kramdown
gems:
- jekyll-sitemap
